name: MCLand
version: 1.0.20260927
main: org.mutantcat.mcland263.Main
api-version: 26.3
author: Mutantcat Working Group
description: 方块猫窝公益服插件（主城保护/死亡不掉落/定期清理/注册登录/传送请求/帮助菜单）
commands:
  register:
    description: 注册当前用户名的密码
    usage: /register 密码 确认密码
  login:
    description: 登录当前用户名
    usage: /login 密码
  password:
    description: 修改当前账号密码
    usage: /password 密码 确认密码
  tp:
    description: 向指定玩家发送传送请求
    usage: /tp 玩家名
  accept:
    description: 接受收到的传送请求
    usage: /accept
